import Head from "next/head";
import React, { FC, ReactNode } from "react";
import Title from "./Title";

interface Props {
  title: string;
  children: ReactNode;
}
export const Layout: FC<Props> = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title} - Next Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-8 py-4">
        <Title>{title}</Title>
        {children}
      </main>
    </>
  );
};
