import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import { ParsedUrlQuery } from "querystring";
import Head from "next/head";
import Link from "next/link";
import { getProduct, getProducts } from "../../lib/product";
import { IProduct } from "../../types/product";
import { ApiError } from "../../lib/api";

interface ProductPageParams extends ParsedUrlQuery {
  id: string;
}

interface ProductPageProps {
  product: IProduct;
}

export const getStaticPaths: GetStaticPaths = async () => {
  const products: IProduct[] = await getProducts();

  return {
    paths: products.map((product) => {
      return { params: { id: product.id.toString() } };
    }),
    fallback: "blocking",
  };
};

export const getStaticProps: GetStaticProps<
  ProductPageProps,
  ProductPageParams
> = async ({ params }) => {
  try {
    const product = await getProduct(params!.id);

    return {
      props: { product },
      revalidate: 60,
    };
  } catch (error) {
    if (error instanceof ApiError && error.status === 404) {
      return { notFound: true };
    }
    throw error;
  }
};

const ProductPage: NextPage<ProductPageProps> = ({ product }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-8 py-4">{product.title}</main>
    </div>
  );
};

export default ProductPage;
