import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { ProductCard } from "../components/ProductCard";
import { getProducts } from "../lib/product";
import { IProduct } from "../types/product";

interface HomePageProps {
  products: IProduct[];
}

export const getStaticProps: GetStaticProps<HomePageProps> = async () => {
  const products = await getProducts();

  return {
    props: { products },
    revalidate: 60,
  };
};

const Home: NextPage<HomePageProps> = ({ products }) => {
  return (
    <div>
      <Head>
        <title>Product page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-8 py-4">
        <ul className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          {products.map((product) => (
            <li key={product.id}>
              <ProductCard product={product} />
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
};

export default Home;
