import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { getProducts } from "../lib/product";
import { IProduct } from "../types/product";

interface HomePageProps {
  products: IProduct[];
}

export const getStaticProps: GetStaticProps<HomePageProps> = async () => {
  const products = await getProducts();

  return { props: { products } };
};

const Home: NextPage<HomePageProps> = ({ products }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {products.map((product) => (
          <li>{product.title}</li>
        ))}
      </main>
    </div>
  );
};

export default Home;
